name: Labels
on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: verify
        uses: yogevbd/enforce-label-action@1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALID_LABELS: major,minor,patch,ci
